import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { NextAuthProvider } from "./lib/next-auth/provider";
import Loading from "./loading";
import { Suspense } from "react";
import Sidebar from "./components/Sidebar";

const notoSansJP = Noto_Sans_JP({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: " Book commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className="bg-[#f5f3f0] dark:bg-[#0f0f0f]">
      <body
        className={`${notoSansJP.className} min-h-screen bg-[#f5f3f0] dark:bg-[#0f0f0f] transition-colors duration-300`}
      >
        <NextAuthProvider>
          <div className="flex flex-col min-h-screen bg-[#f5f3f0] dark:bg-[#0f0f0f] transition-colors duration-300">
            <Header />
            <div className="flex flex-col lg:flex-row max-w-8xl mx-auto px-3 sm:px-6 md:px-8 py-3 sm:py-6 bg-[#f5f3f0] dark:bg-[#0f0f0f] transition-colors duration-300">
              <main className="flex-1 lg:mr-8">
                <Suspense fallback={<Loading />}>{children}</Suspense>
              </main>
              <aside className="w-full lg:w-80 mt-4 lg:mt-0">
                <Suspense fallback={<Loading />}>
                  <Sidebar />
                </Suspense>
              </aside>
            </div>
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
