import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { NextAuthProvider } from "./lib/next-auth/provider";
import Loading from "./loading";
import { Suspense } from "react";
import Sidebar from "./components/Sidebar";

const notoSansJP = Noto_Sans_JP({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: " Book commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={notoSansJP.className}>
        <NextAuthProvider>
          <div className="min-h-screen">
            <Header />
            <div className="flex">
              <main className="flex-1 px-8 py-6">
                <Suspense fallback={<Loading />}>
                  {children}
                </Suspense>
              </main>
              <Sidebar />
            </div>
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
