import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { NextAuthProvider } from "./lib/next-auth/provider";
import Loading from "./loading";
import { Suspense } from "react";
import Sidebar from "./components/Sidebar";

const notoSansJP = Noto_Sans_JP({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: " Book commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={(notoSansJP.className, "min-h-screen bg-gray-100")}>
        <NextAuthProvider>
          <div className="flex flex-col min-h-screen">
            <Header />
            <div className="flex px-4 py-6 flex-col lg:flex-row">
              <main className="flex-1 px-4 sm:px-6 lg:px-8 py-6">
                <Suspense fallback={<Loading />}>{children}</Suspense>
              </main>
              <Sidebar />
            </div>
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
